server:
  port: 8800

spring:
  application:
    name: baomili-admin
  datasource:
    dynamic:
      primary: ums
      strict: false
      datasource:
        ums:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://101.132.155.185:3306/bml_ums?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
          username: David
          password: david210613...
        pms:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://101.132.155.185:3306/bml_pms?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
          username: David
          password: david210613...
        sms:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://101.132.155.185:3306/bml_sms?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
          username: David
          password: david210613...
        oms:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://101.132.155.185:3306/bml_oms?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
          username: David
          password: david210613...

  redis:
    host: 101.132.155.185 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
#    password:  # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.baomili: debug
